export const MOG_FONT_OPTIONS = [
  'Inter',
  'Arial',
  'Helvetica',
  'Verdana',
  'Trebuchet MS',
  'Georgia',
  'Impact',
  'Tahoma',
]

export const MOG_LINE_OPTIONS = [
  { id: 'auto', label: 'Auto' },
  { id: '1', label: '1' },
  { id: '2', label: '2' },
  { id: '3', label: '3' },
]

export const MOG_PACE_OPTIONS = [
  { id: 'soft', label: 'Soft' },
  { id: 'normal', label: 'Normal' },
  { id: 'snappy', label: 'Snappy' },
]

export const MOG_DIRECTION_OPTIONS = [
  { id: 'left', label: 'Left' },
  { id: 'right', label: 'Right' },
  { id: 'up', label: 'Up' },
  { id: 'down', label: 'Down' },
]

export const MOG_EXIT_OPTIONS = [
  { id: 'none', label: 'Hold' },
  { id: 'fade', label: 'Fade Out' },
  { id: 'match', label: 'Match In/Out' },
]

export const MOG_TEXT_GRANULARITY_OPTIONS = [
  { id: 'block', label: 'Block' },
  { id: 'line', label: 'Line' },
  { id: 'word', label: 'Word' },
  { id: 'character', label: 'Character' },
]

export const MOG_MASK_MODE_OPTIONS = [
  { id: 'auto', label: 'Auto' },
  { id: 'none', label: 'Off' },
  { id: 'center', label: 'Center' },
  { id: 'left', label: 'Left' },
  { id: 'right', label: 'Right' },
  { id: 'up', label: 'Up' },
  { id: 'down', label: 'Down' },
]

export const MOG_BACKGROUND_OPTIONS = [
  { id: 'timelineStill', label: 'Timeline Still' },
  { id: 'studio', label: 'Solid' },
  { id: 'checker', label: 'Checker' },
]

export const MOG_ASPECT_RATIO_OPTIONS = [
  { id: '16:9', label: '16:9', width: 16, height: 9 },
  { id: '9:16', label: '9:16', width: 9, height: 16 },
  { id: '1:1', label: '1:1', width: 1, height: 1 },
]

export const MOG_PRESET_CATEGORIES = [
  { id: 'lowerThirds', label: 'Lower Thirds', description: 'Name straps, ribbons, and on-screen IDs.' },
  { id: 'headlines', label: 'Headlines', description: 'Clean central titles and editorial openers.' },
  { id: 'kineticType', label: 'Kinetic Type', description: 'Motion-forward presets with fancier timing and texture.' },
  { id: 'boxTitles', label: 'Box Titles', description: 'Compact UI-style labels and boxed callouts.' },
  { id: 'quoteCards', label: 'Quote Cards', description: 'Quote layouts and text-led cards.' },
  { id: 'ctaBanners', label: 'CTA Banners', description: 'Promos, calls to action, and product pushes.' },
  { id: 'socialVertical', label: 'Social / Vertical', description: 'Layouts tuned for 9:16 and social placements.' },
]

export const MOG_COLOR_PALETTES = [
  {
    id: 'neonMint',
    label: 'Neon Mint',
    textColor: '#F8FAFC',
    accentColor: '#2EE6A6',
    accentColor2: '#34D4FF',
    boxColor: '#08111F',
  },
  {
    id: 'sunsetPunch',
    label: 'Sunset Punch',
    textColor: '#FFF7ED',
    accentColor: '#FB7185',
    accentColor2: '#F59E0B',
    boxColor: '#2A0E1A',
  },
  {
    id: 'electricGrape',
    label: 'Electric Grape',
    textColor: '#FAF5FF',
    accentColor: '#A855F7',
    accentColor2: '#38BDF8',
    boxColor: '#160B29',
  },
  {
    id: 'broadcastGold',
    label: 'Broadcast Gold',
    textColor: '#FFFDF5',
    accentColor: '#F4C430',
    accentColor2: '#FB7185',
    boxColor: '#18120A',
  },
  {
    id: 'emeraldNight',
    label: 'Emerald Night',
    textColor: '#F0FDF4',
    accentColor: '#22C55E',
    accentColor2: '#2DD4BF',
    boxColor: '#08140F',
  },
  {
    id: 'cleanMono',
    label: 'Clean Mono',
    textColor: '#F8FAFC',
    accentColor: '#E2E8F0',
    accentColor2: '#94A3B8',
    boxColor: '#0F172A',
  },
]

function createPreset({
  id,
  name,
  categoryId,
  templateId,
  motionFamily,
  accentStyle = 'line',
  position = 'bottom-left',
  direction = 'left',
  pace = 'snappy',
  exitStyle = 'match',
  lineCount = '2',
  palette = MOG_COLOR_PALETTES[0],
  headline = 'DISCOVER YOUR STORY',
  subheadline = 'Explore MoGraph V1',
  kicker = 'HEADLINE',
  fontFamily = 'Inter',
  fontWeight = '700',
  fontSize = 78,
  subtitleSize = 32,
  letterSpacing = 1,
  textAlign = 'left',
  showBox = true,
  showAccent = true,
  showKicker = true,
  boxOpacity = 84,
  margin = 72,
  padding = 24,
  textGranularity = 'line',
  staggerStep = 0.1,
  blurAmount = 0,
  trackingPull = 0,
  overshootAmount = 0,
  maskMode = 'auto',
  inflateAmount = 0,
  headlineCharacterFx = [],
}) {
  return {
    id,
    name,
    categoryId,
    templateId,
    motionFamily,
    accentStyle,
    position,
    direction,
    pace,
    exitStyle,
    lineCount,
    headline,
    subheadline,
    kicker,
    fontFamily,
    fontWeight,
    fontSize,
    subtitleSize,
    letterSpacing,
    textAlign,
    showBox,
    showAccent,
    showKicker,
    boxOpacity,
    margin,
    padding,
    textGranularity,
    staggerStep,
    blurAmount,
    trackingPull,
    overshootAmount,
    maskMode,
    inflateAmount,
    headlineCharacterFx,
    textColor: palette.textColor,
    accentColor: palette.accentColor,
    accentColor2: palette.accentColor2,
    boxColor: palette.boxColor,
  }
}

function createHeadlineCharacterFx({
  start,
  end,
  xOffset = 0,
  yOffset = 0,
  scale = 1,
  opacity = 1,
  delay = 0,
  tint = 'none',
  rotation = 0,
}) {
  return {
    start,
    end,
    xOffset,
    yOffset,
    scale,
    opacity,
    delay,
    tint,
    rotation,
  }
}

export const MOG_PRESETS = [
  createPreset({
    id: 'dynamic-lower-third',
    name: 'Dynamic Lower Third',
    categoryId: 'lowerThirds',
    templateId: 'lowerThird',
    motionFamily: 'slide',
    accentStyle: 'line',
    position: 'bottom-left',
    palette: MOG_COLOR_PALETTES[0],
  }),
  createPreset({
    id: 'sleek-lower-third-left',
    name: 'Sleek Lower Third Left',
    categoryId: 'lowerThirds',
    templateId: 'lowerThird',
    motionFamily: 'wipe',
    accentStyle: 'bar',
    position: 'bottom-left',
    palette: MOG_COLOR_PALETTES[1],
    kicker: 'NEWSROOM',
    headline: 'BOLD BOX',
    subheadline: 'Shape-backed headline system',
    boxOpacity: 78,
  }),
  createPreset({
    id: 'minimal-title-right',
    name: 'Minimal Title',
    categoryId: 'lowerThirds',
    templateId: 'lowerThird',
    motionFamily: 'reveal',
    accentStyle: 'underline',
    direction: 'right',
    position: 'bottom-right',
    textAlign: 'right',
    palette: MOG_COLOR_PALETTES[5],
    kicker: 'MINIMAL',
    headline: 'MINIMAL TITLE',
    subheadline: 'Editorial lower third',
    showBox: false,
  }),
  createPreset({
    id: 'headline-bold-box',
    name: 'Boldlines',
    categoryId: 'headlines',
    templateId: 'headlineCenter',
    motionFamily: 'boxBuild',
    accentStyle: 'line',
    position: 'center',
    lineCount: '1',
    fontSize: 90,
    subtitleSize: 30,
    textAlign: 'center',
    palette: MOG_COLOR_PALETTES[2],
    kicker: 'FEATURE',
    headline: 'BOLDLINES',
    subheadline: 'Center-stage statement frame',
  }),
  createPreset({
    id: 'gradient-swipe-headline',
    name: 'Gradient Swipe',
    categoryId: 'headlines',
    templateId: 'headlineCenter',
    motionFamily: 'wipe',
    accentStyle: 'ribbon',
    position: 'center',
    direction: 'left',
    lineCount: '2',
    fontSize: 84,
    subtitleSize: 28,
    textAlign: 'center',
    palette: MOG_COLOR_PALETTES[1],
    kicker: 'FEATURED STORY',
    headline: 'GRADIENT SWIPE',
    subheadline: 'Swipe reveal with strong color energy',
  }),
  createPreset({
    id: 'editorial-headline',
    name: 'Editorial Frame',
    categoryId: 'headlines',
    templateId: 'headlineCenter',
    motionFamily: 'slide',
    accentStyle: 'line',
    position: 'upper-center',
    direction: 'up',
    pace: 'normal',
    palette: MOG_COLOR_PALETTES[3],
    kicker: 'EDITORIAL',
    headline: 'DISCOVER YOUR STORY',
    subheadline: 'Playful motion with polished restraint',
    fontFamily: 'Georgia',
    fontWeight: '700',
  }),
  createPreset({
    id: 'minimal-box-title',
    name: 'Minimal Box',
    categoryId: 'boxTitles',
    templateId: 'boxTitle',
    motionFamily: 'boxBuild',
    accentStyle: 'box',
    position: 'top-left',
    palette: MOG_COLOR_PALETTES[4],
    kicker: 'UPDATE',
    headline: 'MINIMAL TILDS',
    subheadline: 'Top-left utility title',
    fontSize: 70,
    subtitleSize: 26,
  }),
  createPreset({
    id: 'gradient-box-title',
    name: 'Gradient Wipe',
    categoryId: 'boxTitles',
    templateId: 'boxTitle',
    motionFamily: 'wipe',
    accentStyle: 'ribbon',
    position: 'top-right',
    direction: 'right',
    textAlign: 'right',
    palette: MOG_COLOR_PALETTES[1],
    kicker: 'SPOTLIGHT',
    headline: 'GRADIENT WIPE',
    subheadline: 'Asymmetric top title block',
  }),
  createPreset({
    id: 'quote-card-punch',
    name: 'Punch Quote',
    categoryId: 'quoteCards',
    templateId: 'quoteCard',
    motionFamily: 'pop',
    accentStyle: 'line',
    position: 'center',
    lineCount: '3',
    textAlign: 'center',
    palette: MOG_COLOR_PALETTES[1],
    kicker: 'QUOTE',
    headline: 'The small details make the motion feel alive.',
    subheadline: 'Creative Director',
    fontSize: 62,
    subtitleSize: 26,
  }),
  createPreset({
    id: 'quote-card-clean',
    name: 'Clean Quote',
    categoryId: 'quoteCards',
    templateId: 'quoteCard',
    motionFamily: 'reveal',
    accentStyle: 'underline',
    position: 'center',
    lineCount: '3',
    textAlign: 'left',
    palette: MOG_COLOR_PALETTES[5],
    kicker: 'EDITOR NOTE',
    headline: 'Preset-driven motion lowers the learning curve fast.',
    subheadline: 'MoGraph V1',
    showBox: true,
    boxOpacity: 76,
    fontSize: 58,
  }),
  createPreset({
    id: 'cta-banner-stripe',
    name: 'CTA Banner',
    categoryId: 'ctaBanners',
    templateId: 'ctaBanner',
    motionFamily: 'slide',
    accentStyle: 'pill',
    position: 'bottom-center',
    direction: 'up',
    lineCount: '1',
    textAlign: 'center',
    palette: MOG_COLOR_PALETTES[2],
    kicker: 'CALL TO ACTION',
    headline: 'CTA BANNERS',
    subheadline: 'Click-through friendly motion',
    fontSize: 56,
    subtitleSize: 22,
  }),
  createPreset({
    id: 'cta-banner-glow',
    name: 'CTA Glow',
    categoryId: 'ctaBanners',
    templateId: 'ctaBanner',
    motionFamily: 'wipe',
    accentStyle: 'pill',
    position: 'bottom-center',
    direction: 'left',
    lineCount: '1',
    textAlign: 'center',
    palette: MOG_COLOR_PALETTES[0],
    kicker: 'PROMO',
    headline: 'SUBSCRIBE NOW',
    subheadline: 'Swipe-in promo ribbon',
    fontSize: 54,
    subtitleSize: 22,
  }),
  createPreset({
    id: 'social-vertical-card',
    name: 'Social Stack',
    categoryId: 'socialVertical',
    templateId: 'socialCard',
    motionFamily: 'pop',
    accentStyle: 'bar',
    position: 'center',
    lineCount: '3',
    textAlign: 'left',
    palette: MOG_COLOR_PALETTES[2],
    kicker: 'VERTICAL',
    headline: 'SOCIAL / VERTICAL',
    subheadline: 'Built for portrait motion graphics',
    fontSize: 64,
    subtitleSize: 24,
  }),
  createPreset({
    id: 'social-neon-card',
    name: 'Neon Promo',
    categoryId: 'socialVertical',
    templateId: 'socialCard',
    motionFamily: 'underlineGrow',
    accentStyle: 'ribbon',
    position: 'center',
    direction: 'down',
    lineCount: '2',
    textAlign: 'center',
    palette: MOG_COLOR_PALETTES[0],
    kicker: 'PROMO DROP',
    headline: 'START PLAYING',
    subheadline: 'High-energy social card',
    fontSize: 68,
    subtitleSize: 24,
  }),
  createPreset({
    id: 'name-role-ribbon',
    name: 'Name + Role',
    categoryId: 'lowerThirds',
    templateId: 'nameRole',
    motionFamily: 'slide',
    accentStyle: 'bar',
    position: 'bottom-left',
    palette: MOG_COLOR_PALETTES[3],
    kicker: 'ON CAMERA',
    headline: 'JORDAN PARK',
    subheadline: 'Creative Director',
    fontSize: 74,
    subtitleSize: 28,
  }),
  createPreset({
    id: 'sports-lower-third',
    name: 'Sports Flash',
    categoryId: 'lowerThirds',
    templateId: 'nameRole',
    motionFamily: 'wipe',
    accentStyle: 'ribbon',
    position: 'bottom-left',
    palette: MOG_COLOR_PALETTES[4],
    kicker: 'LIVE UPDATE',
    headline: 'SCOREBOARD READY',
    subheadline: 'Fast hit lower third',
    fontFamily: 'Impact',
    fontWeight: '700',
    fontSize: 80,
    subtitleSize: 30,
  }),
  createPreset({
    id: 'quote-neon-banner',
    name: 'Neon Quote',
    categoryId: 'quoteCards',
    templateId: 'quoteCard',
    motionFamily: 'underlineGrow',
    accentStyle: 'line',
    position: 'center',
    lineCount: '2',
    textAlign: 'center',
    palette: MOG_COLOR_PALETTES[0],
    kicker: 'QUOTE CARD',
    headline: 'Fun controls keep editors exploring longer.',
    subheadline: 'MoGraph playground',
    fontSize: 60,
    subtitleSize: 24,
  }),
  createPreset({
    id: 'breaking-headline',
    name: 'Breaking Headline',
    categoryId: 'headlines',
    templateId: 'headlineCenter',
    motionFamily: 'slide',
    accentStyle: 'bar',
    position: 'upper-center',
    direction: 'down',
    pace: 'snappy',
    lineCount: '2',
    textAlign: 'center',
    palette: MOG_COLOR_PALETTES[3],
    kicker: 'BREAKING',
    headline: 'STORY MOVES FAST',
    subheadline: 'Big energy top-frame banner',
    fontFamily: 'Impact',
    fontSize: 92,
    subtitleSize: 28,
  }),
  createPreset({
    id: 'quiet-drift-lower-third',
    name: 'Quiet Drift',
    categoryId: 'lowerThirds',
    templateId: 'lowerThird',
    motionFamily: 'drift',
    accentStyle: 'line',
    position: 'bottom-left',
    pace: 'soft',
    palette: MOG_COLOR_PALETTES[5],
    kicker: 'INTERVIEW',
    headline: 'MAYA REED',
    subheadline: 'Founder / Director with soft editorial motion',
    fontSize: 74,
    subtitleSize: 28,
    showBox: false,
    letterSpacing: 0.5,
    blurAmount: 8,
    overshootAmount: 0.06,
  }),
  createPreset({
    id: 'track-in-id',
    name: 'Track In ID',
    categoryId: 'kineticType',
    templateId: 'nameRole',
    motionFamily: 'trackIn',
    accentStyle: 'underline',
    position: 'bottom-left',
    pace: 'normal',
    palette: MOG_COLOR_PALETTES[5],
    kicker: 'ON CAMERA',
    headline: 'JORDAN VALE',
    subheadline: 'Name reveal with tightening letter spacing',
    fontSize: 72,
    subtitleSize: 27,
    showBox: false,
    letterSpacing: 1.4,
    textGranularity: 'character',
    trackingPull: 4.2,
    staggerStep: 0.03,
    blurAmount: 3,
  }),
  createPreset({
    id: 'split-ribbon-lower-third',
    name: 'Split Ribbon',
    categoryId: 'kineticType',
    templateId: 'lowerThird',
    motionFamily: 'splitReveal',
    accentStyle: 'ribbon',
    position: 'bottom-left',
    pace: 'normal',
    palette: MOG_COLOR_PALETTES[4],
    kicker: 'FEATURE DROP',
    headline: 'SPLIT RIBBON',
    subheadline: 'Center-mask reveal with a slim accent strap',
    fontSize: 76,
    subtitleSize: 28,
    boxOpacity: 70,
    maskMode: 'center',
    blurAmount: 2,
  }),
  createPreset({
    id: 'editorial-track-headline',
    name: 'Editorial Track',
    categoryId: 'kineticType',
    templateId: 'headlineCenter',
    motionFamily: 'trackIn',
    accentStyle: 'line',
    position: 'center',
    lineCount: '2',
    textAlign: 'center',
    pace: 'soft',
    palette: MOG_COLOR_PALETTES[5],
    kicker: 'FEATURE STORY',
    headline: 'TYPE TIGHTENS IN',
    subheadline: 'Modern editorial pull-in with restrained polish',
    fontSize: 82,
    subtitleSize: 28,
    showBox: false,
    letterSpacing: 1.6,
    textGranularity: 'character',
    trackingPull: 5.4,
    staggerStep: 0.025,
    blurAmount: 4,
  }),
  createPreset({
    id: 'stagger-stack-headline',
    name: 'Stagger Stack',
    categoryId: 'kineticType',
    templateId: 'headlineCenter',
    motionFamily: 'stagger',
    accentStyle: 'bar',
    position: 'upper-center',
    direction: 'up',
    lineCount: '2',
    textAlign: 'center',
    pace: 'normal',
    palette: MOG_COLOR_PALETTES[2],
    kicker: 'KINETIC TYPE',
    headline: 'LET THE LINES\nARRIVE IN STEPS',
    subheadline: 'Layered line-by-line motion with premium timing',
    fontSize: 82,
    subtitleSize: 28,
    textGranularity: 'line',
    staggerStep: 0.18,
    overshootAmount: 0.04,
  }),
  createPreset({
    id: 'center-split-headline',
    name: 'Center Split',
    categoryId: 'kineticType',
    templateId: 'headlineCenter',
    motionFamily: 'splitReveal',
    accentStyle: 'underline',
    position: 'center',
    lineCount: '1',
    textAlign: 'center',
    pace: 'normal',
    palette: MOG_COLOR_PALETTES[1],
    kicker: 'NOW PLAYING',
    headline: 'CENTER SPLIT',
    subheadline: 'A clean mask reveal that opens from the middle',
    fontSize: 88,
    subtitleSize: 28,
    showBox: false,
    maskMode: 'center',
    inflateAmount: 0.28,
  }),
  createPreset({
    id: 'utility-tag-track',
    name: 'Utility Tag',
    categoryId: 'boxTitles',
    templateId: 'boxTitle',
    motionFamily: 'trackIn',
    accentStyle: 'box',
    position: 'top-left',
    pace: 'normal',
    palette: MOG_COLOR_PALETTES[5],
    kicker: 'TAG',
    headline: 'UTILITY TAG',
    subheadline: 'Compact UI-style label with tightening type',
    fontSize: 64,
    subtitleSize: 24,
    letterSpacing: 1.2,
    boxOpacity: 68,
    textGranularity: 'character',
    trackingPull: 3.6,
    staggerStep: 0.03,
  }),
  createPreset({
    id: 'glass-drift-quote',
    name: 'Glass Drift',
    categoryId: 'quoteCards',
    templateId: 'quoteCard',
    motionFamily: 'drift',
    accentStyle: 'line',
    position: 'center',
    lineCount: '3',
    textAlign: 'left',
    pace: 'soft',
    palette: MOG_COLOR_PALETTES[5],
    kicker: 'EDITOR NOTE',
    headline: 'Sharper motion comes from timing and restraint, not noise.',
    subheadline: 'Creative Direction',
    fontSize: 58,
    subtitleSize: 25,
    boxOpacity: 58,
    blurAmount: 6,
    overshootAmount: 0.04,
  }),
  createPreset({
    id: 'stagger-social-card',
    name: 'Stagger Social',
    categoryId: 'kineticType',
    templateId: 'socialCard',
    motionFamily: 'stagger',
    accentStyle: 'pill',
    position: 'center',
    lineCount: '2',
    textAlign: 'center',
    pace: 'normal',
    palette: MOG_COLOR_PALETTES[0],
    kicker: 'VERTICAL DROP',
    headline: 'STACK THE MESSAGE',
    subheadline: 'Staggered social opener built for 9:16 layouts',
    fontSize: 66,
    subtitleSize: 24,
    textGranularity: 'word',
    staggerStep: 0.12,
    blurAmount: 5,
    overshootAmount: 0.05,
  }),
  createPreset({
    id: 'split-cta-banner',
    name: 'Split CTA',
    categoryId: 'kineticType',
    templateId: 'ctaBanner',
    motionFamily: 'splitReveal',
    accentStyle: 'pill',
    position: 'bottom-center',
    lineCount: '1',
    textAlign: 'center',
    pace: 'normal',
    palette: MOG_COLOR_PALETTES[3],
    kicker: 'LIMITED DROP',
    headline: 'JOIN THE WAITLIST',
    subheadline: 'Modern center reveal for promos and product tags',
    fontSize: 56,
    subtitleSize: 22,
    maskMode: 'center',
    inflateAmount: 0.2,
  }),
  createPreset({
    id: 'morph-bloom-headline',
    name: 'Morph Bloom',
    categoryId: 'kineticType',
    templateId: 'headlineCenter',
    motionFamily: 'inflateMorph',
    accentStyle: 'line',
    position: 'center',
    lineCount: '1',
    textAlign: 'center',
    pace: 'soft',
    palette: MOG_COLOR_PALETTES[5],
    kicker: 'KINETIC TYPE',
    headline: 'MORPH BLOOM',
    subheadline: 'Character-led inflate reveal with a cleaner premium finish',
    fontSize: 92,
    subtitleSize: 26,
    showBox: false,
    letterSpacing: 0.4,
    textGranularity: 'character',
    staggerStep: 0.028,
    blurAmount: 2,
    trackingPull: -1.6,
    overshootAmount: 0.08,
    maskMode: 'none',
    inflateAmount: 1.4,
  }),
  createPreset({
    id: 'balloon-title-card',
    name: 'Balloon Title',
    categoryId: 'kineticType',
    templateId: 'headlineCenter',
    motionFamily: 'inflateMorph',
    accentStyle: 'pill',
    position: 'center',
    lineCount: '2',
    textAlign: 'center',
    pace: 'normal',
    palette: MOG_COLOR_PALETTES[0],
    kicker: 'FEATURE OPEN',
    headline: 'BALLOON\nTITLE CARD',
    subheadline: 'A chunkier inflate with more blur and a friendlier feel',
    fontSize: 84,
    subtitleSize: 28,
    showBox: false,
    letterSpacing: 0.2,
    textGranularity: 'character',
    staggerStep: 0.04,
    blurAmount: 5,
    trackingPull: -0.8,
    overshootAmount: 0.12,
    maskMode: 'none',
    inflateAmount: 1.75,
  }),
  createPreset({
    id: 'vertical-pop-morph',
    name: 'Vertical Pop Morph',
    categoryId: 'kineticType',
    templateId: 'socialCard',
    motionFamily: 'inflateMorph',
    accentStyle: 'bar',
    position: 'center',
    lineCount: '2',
    textAlign: 'center',
    pace: 'normal',
    palette: MOG_COLOR_PALETTES[3],
    kicker: 'SOCIAL DROP',
    headline: 'POP THE\nMESSAGE',
    subheadline: 'Built to feel bolder in 9:16 without turning into chaos',
    fontSize: 72,
    subtitleSize: 24,
    boxOpacity: 54,
    showBox: false,
    letterSpacing: 0.3,
    textGranularity: 'character',
    staggerStep: 0.035,
    blurAmount: 4,
    trackingPull: -1.2,
    overshootAmount: 0.1,
    maskMode: 'none',
    inflateAmount: 1.55,
  }),
  createPreset({
    id: 'offset-burst-headline',
    name: 'Offset Burst',
    categoryId: 'kineticType',
    templateId: 'headlineCenter',
    motionFamily: 'trackIn',
    accentStyle: 'line',
    position: 'center',
    lineCount: '1',
    textAlign: 'center',
    pace: 'normal',
    palette: MOG_COLOR_PALETTES[0],
    kicker: 'CHARACTER FX',
    headline: 'OFFSET BURST',
    subheadline: 'Letters break formation with side pushes and angular accents',
    fontSize: 86,
    subtitleSize: 26,
    showBox: false,
    letterSpacing: 0.5,
    textGranularity: 'character',
    staggerStep: 0.03,
    blurAmount: 3,
    trackingPull: 1.8,
    overshootAmount: 0.06,
    headlineCharacterFx: [
      createHeadlineCharacterFx({
        start: 1,
        end: 2,
        xOffset: -12,
        yOffset: -8,
        scale: 1.08,
        delay: 0.02,
        tint: 'accent',
        rotation: -8,
      }),
      createHeadlineCharacterFx({
        start: 8,
        end: 11,
        xOffset: 10,
        yOffset: 4,
        scale: 1.05,
        delay: 0.05,
        tint: 'accent2',
        rotation: 7,
      }),
    ],
  }),
  createPreset({
    id: 'tilt-pop-headline',
    name: 'Tilt Pop',
    categoryId: 'kineticType',
    templateId: 'headlineCenter',
    motionFamily: 'inflateMorph',
    accentStyle: 'pill',
    position: 'center',
    lineCount: '1',
    textAlign: 'center',
    pace: 'soft',
    palette: MOG_COLOR_PALETTES[1],
    kicker: 'PLAYFUL TYPE',
    headline: 'TILT POP',
    subheadline: 'Inflated letter groups with opposing tilts for a punchier lockup',
    fontSize: 88,
    subtitleSize: 26,
    showBox: false,
    letterSpacing: 0.15,
    textGranularity: 'character',
    staggerStep: 0.035,
    blurAmount: 2,
    trackingPull: -0.6,
    overshootAmount: 0.1,
    maskMode: 'none',
    inflateAmount: 1.2,
    headlineCharacterFx: [
      createHeadlineCharacterFx({
        start: 1,
        end: 4,
        xOffset: -8,
        yOffset: -8,
        scale: 1.08,
        delay: 0.03,
        tint: 'accent',
        rotation: -8,
      }),
      createHeadlineCharacterFx({
        start: 5,
        end: 8,
        xOffset: 9,
        yOffset: 4,
        scale: 1.05,
        delay: 0.05,
        tint: 'accent2',
        rotation: 9,
      }),
    ],
  }),
  createPreset({
    id: 'angle-drive-lower-third',
    name: 'Angle Drive',
    categoryId: 'kineticType',
    templateId: 'lowerThird',
    motionFamily: 'stagger',
    accentStyle: 'underline',
    position: 'bottom-left',
    direction: 'up',
    pace: 'normal',
    palette: MOG_COLOR_PALETTES[3],
    kicker: 'ON SCREEN',
    headline: 'ANGLE DRIVE',
    subheadline: 'A sharper lower-third with custom nudges on the opening and finish',
    fontSize: 72,
    subtitleSize: 26,
    textGranularity: 'character',
    staggerStep: 0.045,
    blurAmount: 2,
    trackingPull: 1.6,
    overshootAmount: 0.04,
    headlineCharacterFx: [
      createHeadlineCharacterFx({
        start: 1,
        end: 3,
        xOffset: -10,
        yOffset: -4,
        scale: 1.05,
        delay: 0.02,
        tint: 'accent',
        rotation: -6,
      }),
      createHeadlineCharacterFx({
        start: 6,
        end: 10,
        xOffset: 10,
        yOffset: 3,
        scale: 1.04,
        delay: 0.04,
        tint: 'accent2',
        rotation: 5,
      }),
    ],
  }),
  createPreset({
    id: 'split-stack-fx',
    name: 'Split Stack FX',
    categoryId: 'kineticType',
    templateId: 'headlineCenter',
    motionFamily: 'splitReveal',
    accentStyle: 'line',
    position: 'center',
    lineCount: '2',
    textAlign: 'center',
    pace: 'normal',
    palette: MOG_COLOR_PALETTES[1],
    kicker: 'MULTI-LINE FX',
    headline: 'SHIFT\nTHE FRAME',
    subheadline: 'Top and bottom lines get different letter pushes across the break',
    fontSize: 82,
    subtitleSize: 26,
    showBox: false,
    textGranularity: 'character',
    staggerStep: 0.035,
    blurAmount: 2,
    trackingPull: 1.2,
    overshootAmount: 0.06,
    maskMode: 'center',
    inflateAmount: 0.45,
    headlineCharacterFx: [
      createHeadlineCharacterFx({
        start: 1,
        end: 5,
        xOffset: -9,
        yOffset: -6,
        scale: 1.06,
        delay: 0.03,
        tint: 'accent',
        rotation: -5,
      }),
      createHeadlineCharacterFx({
        start: 6,
        end: 8,
        xOffset: 4,
        yOffset: 4,
        scale: 1.03,
        delay: 0.05,
        tint: 'accent2',
        rotation: 4,
      }),
      createHeadlineCharacterFx({
        start: 9,
        end: 13,
        xOffset: 10,
        yOffset: -2,
        scale: 1.05,
        delay: 0.07,
        tint: 'accent',
        rotation: 6,
      }),
    ],
  }),
  createPreset({
    id: 'ladder-rise-title',
    name: 'Ladder Rise',
    categoryId: 'kineticType',
    templateId: 'headlineCenter',
    motionFamily: 'stagger',
    accentStyle: 'bar',
    position: 'upper-center',
    direction: 'up',
    lineCount: '2',
    textAlign: 'center',
    pace: 'normal',
    palette: MOG_COLOR_PALETTES[2],
    kicker: 'STACKED TYPE',
    headline: 'BUILD\nIT LOUD',
    subheadline: 'A two-line stack with separate motion attitude on each row',
    fontSize: 80,
    subtitleSize: 27,
    textGranularity: 'character',
    staggerStep: 0.045,
    blurAmount: 3,
    trackingPull: 1.2,
    overshootAmount: 0.05,
    headlineCharacterFx: [
      createHeadlineCharacterFx({
        start: 1,
        end: 5,
        xOffset: -5,
        yOffset: -8,
        scale: 1.07,
        delay: 0.02,
        tint: 'accent',
        rotation: -6,
      }),
      createHeadlineCharacterFx({
        start: 6,
        end: 11,
        xOffset: 8,
        yOffset: 4,
        scale: 1.04,
        delay: 0.05,
        tint: 'accent2',
        rotation: 5,
      }),
    ],
  }),
  createPreset({
    id: 'vertical-echo-stack',
    name: 'Vertical Echo Stack',
    categoryId: 'socialVertical',
    templateId: 'socialCard',
    motionFamily: 'inflateMorph',
    accentStyle: 'pill',
    position: 'center',
    lineCount: '3',
    textAlign: 'center',
    pace: 'soft',
    palette: MOG_COLOR_PALETTES[0],
    kicker: 'VERTICAL FX',
    headline: 'MOVE\nWITH\nSTYLE',
    subheadline: 'Three lines, three letter groups, tuned for a bold 9:16 feel',
    fontSize: 70,
    subtitleSize: 24,
    showBox: false,
    textGranularity: 'character',
    staggerStep: 0.04,
    blurAmount: 3,
    trackingPull: -0.6,
    overshootAmount: 0.11,
    maskMode: 'none',
    inflateAmount: 1.15,
    headlineCharacterFx: [
      createHeadlineCharacterFx({
        start: 1,
        end: 4,
        xOffset: -7,
        yOffset: -8,
        scale: 1.07,
        delay: 0.03,
        tint: 'accent',
        rotation: -6,
      }),
      createHeadlineCharacterFx({
        start: 5,
        end: 8,
        xOffset: 6,
        yOffset: 3,
        scale: 1.04,
        delay: 0.05,
        tint: 'accent2',
        rotation: 4,
      }),
      createHeadlineCharacterFx({
        start: 9,
        end: 13,
        xOffset: 9,
        yOffset: -2,
        scale: 1.06,
        delay: 0.08,
        tint: 'accent',
        rotation: 6,
      }),
    ],
  }),
]

export const DEFAULT_MOG_PRESET_ID = MOG_PRESETS[0].id

export function getMogPresetById(id) {
  return MOG_PRESETS.find((preset) => preset.id === id) || MOG_PRESETS[0]
}

export function buildMogStateFromPreset(preset) {
  const resolved = preset || MOG_PRESETS[0]
  return {
    presetId: resolved.id,
    headline: resolved.headline,
    subheadline: resolved.subheadline,
    kicker: resolved.kicker,
    lineCount: resolved.lineCount,
    fontFamily: resolved.fontFamily,
    fontWeight: resolved.fontWeight,
    fontSize: resolved.fontSize,
    subtitleSize: resolved.subtitleSize,
    textAlign: resolved.textAlign,
    letterSpacing: resolved.letterSpacing,
    duration: 3.5,
    animationDurationScale: 1,
    textGranularity: resolved.textGranularity || 'line',
    staggerStep: resolved.staggerStep ?? 0.1,
    blurAmount: resolved.blurAmount ?? 0,
    trackingPull: resolved.trackingPull ?? 0,
    overshootAmount: resolved.overshootAmount ?? 0,
    maskMode: resolved.maskMode || 'auto',
    inflateAmount: resolved.inflateAmount ?? 0,
    headlineCharacterFx: Array.isArray(resolved.headlineCharacterFx)
      ? resolved.headlineCharacterFx.map((rule, index) => ({
        id: `${resolved.id}-fx-${index + 1}`,
        start: rule.start ?? 1,
        end: rule.end ?? rule.start ?? 1,
        xOffset: rule.xOffset ?? 0,
        yOffset: rule.yOffset ?? 0,
        scale: rule.scale ?? 1,
        opacity: rule.opacity ?? 1,
        delay: rule.delay ?? 0,
        tint: rule.tint ?? 'none',
        rotation: rule.rotation ?? 0,
      }))
      : [],
    pace: resolved.pace,
    direction: resolved.direction,
    exitStyle: resolved.exitStyle,
    textColor: resolved.textColor,
    accentColor: resolved.accentColor,
    accentColor2: resolved.accentColor2,
    boxColor: resolved.boxColor,
    boxOpacity: resolved.boxOpacity,
    margin: resolved.margin,
    padding: resolved.padding,
    showBox: resolved.showBox,
    showAccent: resolved.showAccent,
    showKicker: resolved.showKicker,
    animationStyle: resolved.motionFamily,
    backgroundMode: 'timelineStill',
    aspectRatio: '16:9',
    assetName: resolved.name,
  }
}
